### ISSUE TITLE
Tests disappear

### ISSUE THREAD

**Issue by thebarty** [practicalmeteor/mocha#28]
Hi guys,

this is really strange... from time to time tests disappear in the browser status-window... for example right now I got 13 tests, BUT only 1 test is shown!

Anyone else experiencing this issue?

**Comment by thebarty** [comment]
Ok... I have found the solution... grep seems to be a feature to filter tests from the url `http://localhost:3100/?grep=`

**Comment by jsep** [comment]
Yes mocha filter the the tests using grep query string, for example if you click a test only that test will run.
