### ISSUE TITLE
Is there a way to disable a package when testing?

### ISSUE THREAD

**Issue by knoid** [practicalmeteor/mocha#29]

**Comment by rbabayoff** [comment]
2 options:
1. Remove it from the meteor app before testing the app
2. Put all your code in packages, which with meteor 1.3 became much less cumbersome, so no need to add each source code file individually, and just test the packages you want. If it's not your own package you want to disable, just create a package that adds the 3rd party one and don't test it.

I'm curious in regards to your specific use case, why do you need that?

**Comment by knoid** [comment]
Thanks for the easy solution!

My problem is that part of a package I'm trying to use assumes I use another accounts-password when that's not the case, I'm using it for its other features.
