### ISSUE TITLE
Server-side tests abort on exception without any report

### ISSUE THREAD

**Issue by rhettlivingston** [practicalmeteor/mocha#34]
While developing using the new guide's advice on Methods and Testing and an approach derived from the todos example app, I have encountered numerous cases of my server-side tests simply aborting on exceptions without any indication that they ever even started. No exceptions show in any consoles either. The only indication that it happened is that the completion indicator never hits 100%. So, something is still alive and waiting for them, but no timeouts ever occur either.

This can be particularly troublesome when only one test in many is having the problem. Since the fact that the test did in fact start doesn't get reported, you have to compare which ones did get reported to your code to even figure out what test to look at.

The particular exception that gives me the most trouble is the one at [line 425 in collection2.js](https://github.com/aldeed/meteor-collection2-core/blob/eaba89abd9f9de1a0081c9cf4688eea204e1e049/lib/collection2.js#L425) that seems to get thrown any time an exception is thrown by autoValue or defaultValue code in the schema. This is a commonly used package and autoValue's can get tricky to write as well as to unit test, so probably not an uncommon problem for pm mocha users.

To duplicate my issue, just grab the latest [todos example](https://github.com/meteor/todos), npm install, test using 

> meteor test --driver-package practicalmeteor:mocha

as usual to see what server-side tests look like when they pass, change /imports/api/lists/lists.js line 40 from 

>  userId: { type: String, regEx: SimpleSchema.RegEx.Id, optional: true },

to

>  userId: { type: String, regEx: SimpleSchema.RegEx.Id, defaultValue: this.userId },

and then rerun the unit tests. "this.userId" will be undefined when referenced by aldeed:SimpleSchema and throw an exception that will be caught and rethrown by collection2-core after which the test will cease with no report.

Note that wrapping my calls in chai.assert.Throws or doesNotThrow didn't help one bit. The exception bypasses everything.

See also meteor/todos#122.

**Comment by jsep** [comment]
Thank you for reporting this issue. I was able to reproduce this. I'm working to fix this issue

**Comment by jsep** [comment]
Good news  @rhettlivingston I've publish a release version of the package that should fix this issue. Please  add `practicalmeteor:mocha@2.4.6-rc.2` and let me know any other issue.

**Comment by rhettlivingston** [comment]
Sorry that it took a while. I bit on the ubuntu 16.04 upgrade too quick. Took me a while to battle the issues.

I'm happy to report that I tested this in two applications, both making sure nothing that had been working before broke and making sure that it did fix the problem if I intentionally broke code to throw the exceptions that weren't caught before. All was great! Thank you!

One more possibly quick question. I've encountered issues when debugging server-side test code that seem to involve the runtime not getting fully reset in some way after a change is made. It sometimes takes a while for my thick head to realize that my change isn't taking effect and take the time to kill meteor and re-invoke it to get a clean run. One way to perhaps duplicate it is to have a test call a method that is defined at module level and then move that definition into the test or vice versa. Everything seems sort of OK. The test console running in the browser will automatically reload after the server recompiles and act as if nothing special happened. But if you hit F5, the tests will fail with something like

Error: A method named 'noArgsMethod' is already defined
    at packages/ddp-server/livedata_server.js:1548:15
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at Server.methods (packages/ddp-server/livedata_server.js:1544:7)
    at new ValidatedMethod (packages/mdg:validated-method/validated-method.js:48:21)
    at Context.<anonymous> (packages/local-test:rlivingston:simple-schema-mixin/simple-schema-mixin-tests.js:89:26)
    at run (packages/practicalmeteor:mocha/meteor/src/setup/SetupRunnables.js:117:18)

So, the old definition is somehow hanging around across a recompile!!! Is this expected behavior. The same test works great client side. It's only on the server-side that I see this. If it isn't expected and you can't quickly duplicate it, I'll try to come up with a test involving the todos app and make another bug report.

**Comment by jsep** [comment]
Good to know its working great @rhettlivingston, what you say about server-side debugging is interesting, I would like to know how are you debugging your app?

**Comment by rhettlivingston** [comment]
This is only really happening when I'm writing tests. I'll 
1. start `meteor test-packages ./ --driver-package practicalmeteor:mocha`, 
2. open a browser to http://localhost:3000/, 
3. open simple-schema-mixin-tests.js in this case in an editor, 
4. write or modify a test, 
5. save it, 
6. meteor will detect the save and automatically rebuild, 
7. then I'll look over at the browser and see how the test ran,
8. if necessary, back to step 4.

This is really how I work when writing most anything, not just tests. Incrementally. The approach works great when I'm on the client or writing server-side code running outside of test mode. On the server-side when running tests though, not always so.

**Comment by rbabayoff** [comment]
Solved in 2.4.5_2. Closing this.
