### ISSUE TITLE
Feature request: Quickly filtering skipped/pending tests

### ISSUE THREAD

**Issue by dovrosenberg** [practicalmeteor/mocha#36]
It would be great if there were a filter at the top of the results to list the skipped/pending tests separately from the passed and failed ones.

I often create a lot of empty tests as placeholders when I'm fleshing out a new section and it would be great to be able to quickly get a list of where these all are so I can then go back and fill them out.

Thanks!

**Comment by rbabayoff** [comment]
@dovrosenberg, we're using a slightly modified version of the original [mocha html reporter](https://mochajs.org/#reporters), this should probably be filed at the mocha [repo](https://github.com/mochajs/mocha).

**Comment by dovrosenberg** [comment]
Got it. After further investigation - already done: https://github.com/mochajs/mocha/issues/2150
