### ISSUE TITLE
HTML Reporter Layout Issue: Overflow Hidden on Body

### ISSUE THREAD

**Issue by joncursi** [practicalmeteor/mocha#40]
After the test suite generates an HTML report via the command

```
meteor test --driver-package practicalmeteor:mocha --port 5000
```

the HTML body tag, for some reason, **sometimes** receives an inline style of `overflow: hidden` which prevents the developer from scrolling vertically through the tests.

![screen shot 2016-05-10 at 5 17 25 pm](https://cloud.githubusercontent.com/assets/4974609/15162879/566c4da0-16d3-11e6-8850-240bf471de0f.png)

Any idea why this happens, and why intermittently? Thanks!

**Comment by jsep** [comment]
That's weird :confused: , I don't have that and I can scroll through my tests.

Please try to use the latest version which is `2.4.5_2`.

**Comment by joncursi** [comment]
Dang, I'm already using the latest version. I notice that 0.5 seconds after the HTML reporter loads, the inline style gets applied. I wonder if it could be from the dependencies that I am importing throughout my tests?

Is the HTML reporter by chance not isolated from such imports?

**Comment by jsep** [comment]
Interesting, according to meteor guide when running in "unit test mode" it will only include the files that you are importing, maybe some dependency it's doing that?

Some times even browser extensions can mess up with the layout.

But the package `praticalmeteo:mocha` it's not  adding the inline style.

The project has some demos a test app and a test package, if you want you can try to run those demos.

```
git clone git@github.com:practicalmeteor/meteor-mocha.git
cd meteor-mocha
git checkout meteor-v2.4.5_2 # In this branch the demos are updated
cd meteor/test-app
meteor test --driver-package practicalmeteor:mocha
```

Let me know any progress.

**Comment by joncursi** [comment]
Closing, since it's likely not an issue with this project itself.

**Comment by carinakoo** [comment]
In case anyone else has this issue, for me the source was a client side test which opened a modal and set `overflow:hidden` on the body. Closing the modal in the test solved it.
