### ISSUE TITLE
Cannot Run --full-app Test on Meteor 1.3.2.4

### ISSUE THREAD

**Issue by vu-bui** [practicalmeteor/mocha#41]
When I execute full app test by running `meteor test --full-app --driver-package practicalmeteor:mocha`, none of the `.app-spec.` files are executed. Things happen the same for Meteor's [todos](https://github.com/meteor/todos) app. It was fine if I didn't upgrade Meteor version to the lastest 1.3.2.4. The original version of the app is 1.3, which will be run on 1.3.0_3.

<img width="1231" alt="screen shot 2016-05-13 at 1 44 51 am" src="https://cloud.githubusercontent.com/assets/5633851/15226489/1f29a30c-18ad-11e6-9a2b-f76cbb868df3.png">

**Comment by Dev1an** [comment]
Dear Vu Bui,

The email sent to info@devian.tk with subject
"[practicalmeteor/meteor-mocha] Cannot Run --full-app Test on Meteor"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to info@devian.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by jsep** [comment]
Thanks @vu-bui,  I could reproduce this, however it seems to be Meteor it's not running `*.app-test*` or  `*.app-spec*` files.

@tmeasday any ideas about this?.

**Comment by Dev1an** [comment]
Dear Juan Sepulveda,

The email sent to info@devian.tk with subject
"Re: [practicalmeteor/meteor-mocha] Cannot Run --full-app Test on"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to info@devian.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by ramijarrar** [comment]
Looks like we have a fix for this on devel: https://github.com/meteor/meteor/commit/b196478146918cc81b923706087e0034a571080d

**Comment by Dev1an** [comment]
Dear ramijarrar,

The email sent to info@devian.tk with subject
"Re: [practicalmeteor/meteor-mocha] Cannot Run --full-app Test on"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to info@devian.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by vu-bui** [comment]
Thanks guys, so this is actually Meteor's problem and it has already been fixed on Meteor.

As it's not related to practicalmeteor:mocha, I'll close it for now.

**Comment by Dev1an** [comment]
Dear Vu Bui,

The email sent to info@devian.tk with subject
"Re: [practicalmeteor/meteor-mocha] Cannot Run --full-app Test on"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to info@devian.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by jsep** [comment]
@Dev1an can you stop the spam? please....
