### ISSUE TITLE
New version requires npm dependencies and fails to start test

### ISSUE THREAD

**Issue by theodorDiaconu** [practicalmeteor/mocha#52]
It worked previously.

```
W20160621-09:51:15.774(3)? (STDERR)           
W20160621-09:51:15.776(3)? (STDERR) /home/theodor/.meteor/packages/meteor-tool/.1.3.2_4.g1nly0++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160621-09:51:15.776(3)? (STDERR)                                             throw(ex);
W20160621-09:51:15.776(3)? (STDERR)                                                   ^
W20160621-09:51:15.778(3)? (STDERR) Error: Cannot find module 'debug'
W20160621-09:51:15.778(3)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20160621-09:51:15.779(3)? (STDERR)     at Function.Module._load (module.js:280:25)
W20160621-09:51:15.779(3)? (STDERR)     at Module.require (module.js:364:17)
W20160621-09:51:15.779(3)? (STDERR)     at require (module.js:380:17)
W20160621-09:51:15.779(3)? (STDERR)     at Object.<anonymous> (/home/theodor/.meteor/packages/practicalmeteor_mocha/.2.4.5_3.nshwyr++os+web.browser+web.cordova/npm/node_modules1/mocha/lib/runnable.js:7:13)
W20160621-09:51:15.779(3)? (STDERR)     at Module._compile (module.js:456:26)
W20160621-09:51:15.779(3)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160621-09:51:15.780(3)? (STDERR)     at Module.load (module.js:356:32)
W20160621-09:51:15.780(3)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160621-09:51:15.780(3)? (STDERR)     at Module.require (module.js:364:17)
W20160621-09:51:15.781(3)? (STDERR)     at require (module.js:380:17)
W20160621-09:51:15.781(3)? (STDERR)     at Object.<anonymous> (/home/theodor/.meteor/packages/practicalmeteor_mocha/.2.4.5_3.nshwyr++os+web.browser+web.cordova/npm/node_modules1/mocha/lib/test.js:5:16)
```

**Comment by theodorDiaconu** [comment]
Running it like:

`meteor test-packages packages/framework --driver-package=practicalmeteor:mocha --port 3080`

**Comment by theodorDiaconu** [comment]
The solution was to do meteor reset, then install version 2.4.5_2 (using meteor add)
Then run it. Hope it will be fixed soon.

**Comment by rbabayoff** [comment]
@tmeasday this looks like a meteor bug related to npm dependency installations, not a mocha one, right?

**Comment by tmeasday** [comment]
Hmm, this looks a bit strange. If you are `Npm.depend`-ing on `debug` (which it [appears you are](https://github.com/practicalmeteor/meteor-mocha/blob/meteor/package.js)) then I don't have a good explanation of what could be causing this.

@theodorDiaconu are you saying the problem exists in `2.4.5_3` but not `2.4.5_2`?

**Comment by theodorDiaconu** [comment]
@tmeasday @rbabayoff 
This was the flow of things:

Everything was working fine. Tests were running. 
I updated to Meteor 1.3.3.1 and did a project reset
Tests began to fail with that error. I assumed it's Meteor version.
I downgraded to Meteor 1.3.2.4
Same problem
I knew it was previously working so I tried --driver-package=practicalmeteor:mocha@2.4.5_2 . This does not work. So I installed it using meteor add @, then ran the tests.

Sorry I know it's vague and weird, but I did not invent that error :). I will come back when I have more information.

**Comment by PolGuixe** [comment]
I have the same issue. This is weird. @tmeasday if you want to reproduce it, take the todos-react app. Do a `meteor update` and then `npm run test-watch`. And you'll get the error. 

And the todos app is using: `practicalmeteor:mocha@2.1.1-rc.1`

**Comment by tmeasday** [comment]
@PolGuixe that branch appeared to be missing `session` from its `.meteor/packages` but apart from that is working fine when I update it..

**Comment by PolGuixe** [comment]
@tmeasday I am still getting this error: 

```
W20160629-11:53:43.313(2)? (STDERR)
W20160629-11:53:43.675(2)? (STDERR) /Users/PolGuixe/.meteor/packages/meteor-tool/.1.3.4_1.1rownv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160629-11:53:43.675(2)? (STDERR)                             throw(ex);
W20160629-11:53:43.676(2)? (STDERR)                                   ^
W20160629-11:53:43.688(2)? (STDERR) Error: Cannot find module 'debug'
W20160629-11:53:43.688(2)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20160629-11:53:43.689(2)? (STDERR)     at Function.Module._load (module.js:280:25)
W20160629-11:53:43.689(2)? (STDERR)     at Module.require (module.js:364:17)
W20160629-11:53:43.689(2)? (STDERR)     at require (module.js:380:17)
W20160629-11:53:43.689(2)? (STDERR)     at Object.<anonymous> (/Users/PolGuixe/.meteor/packages/practicalmeteor_mocha/.2.4.5_4.19hsmgq++os+web.browser+web.cordova/npm/node_modules1/mocha/lib/runnable.js:7:13)
W20160629-11:53:43.690(2)? (STDERR)     at Module._compile (module.js:456:26)
W20160629-11:53:43.690(2)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160629-11:53:43.690(2)? (STDERR)     at Module.load (module.js:356:32)
W20160629-11:53:43.691(2)? (STDERR)     at Module.Mp.load (/Users/PolGuixe/.meteor/packages/babel-compiler/.6.8.3.1gmqhkh++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)
W20160629-11:53:43.692(2)? (STDERR)     at Function.Module._load (module.js:312:12)
```

**Comment by PolGuixe** [comment]
I have done the following. 

Create a new app:
`meteor create test-meteor`

Add practical meteor mocha: 
`cd test-meteor`
`meteor add practicalmeteor:mocha`

Run the app: 
`meteor`

Works ok. 

Run the tests: 
`meteor test --driver-package=practicalmeteor:mocha`

Fails with the Error on the comment above. 

Downgrade to 1.3.1: 
`meteor update  --release 1.3.1`

Run tests again: 
`meteor test --driver-package=practicalmeteor:mocha`

And it works....

**Comment by PolGuixe** [comment]
@tmeasday Ok, don't ask me what happened. But I've tried it on a different machine and it was working. 

So I reinstalled meteor on the machine I was having the problem and now it works...

**Comment by rbabayoff** [comment]
@theodorDiaconu can you also reinstall meteor to see if it solves it?

**Comment by aldeed** [comment]
I had the same problem trying to run the repro from https://github.com/practicalmeteor/meteor-mocha/issues/55, and reinstalling Meteor fixed it.

**Comment by jsep** [comment]
Reinstalling meteor seems to solve this issue.
