### ISSUE TITLE
If the tests are inside a folder called tests it won't find them

### ISSUE THREAD

**Issue by PolGuixe** [practicalmeteor/mocha#56]
files called `*.test[s].js` inside a `**/tests` folder are not executed by the runner.

**Comment by rbabayoff** [comment]
@PolGuixe I think this is by design, the way meteor implemented it. Folder named tests are ignored for backward compatibility reasons. Am I correct, @tmeasday?

**Comment by PolGuixe** [comment]
@rbabayoff Could we point the package to search in such folders? With some sort of indicator e.g `/**/tests/**/*` or flag?

**Comment by tmeasday** [comment]
Yeah, this is by design, and part of the Meteor build system.

Kind of complicated why we decided to go this way, not sure it was the right call. But the idea is that you put the tests next to the thing you are testing.
