### ISSUE TITLE
Use `runTests` function for Meteor 1.3

### ISSUE THREAD

**Issue by aldeed** [practicalmeteor/mocha#59]
I noticed that this package is still running tests on client startup. This means it's running tests when dispatch:mocha-phantomjs is used as the driver for the current run (assuming both pkgs are added), which doesn't really cause problems but shows confusing logging in the console and is inefficient.

The problem is here: https://github.com/practicalmeteor/meteor-mocha/blob/meteor/meteor/src/lib/MochaRunner.coffee#L178

The fix is to define and export a `runTests` function like `dispatch:mocha-phantomjs` does here: https://github.com/DispatchMe/meteor-mocha-phantomjs/blob/master/client.js#L6

Meteor 1.3 will run the exported function for the current driver package only.

This would be a breaking change for older versions of Meteor. If there is some way to check the current Meteor version in code, then you can keep the current Meteor.startup for Meteor <1.3.

**Comment by jsep** [comment]
Yes you are right, I'm going to fix this after in the next release.
