### ISSUE TITLE
meteor add practicalmeteor:mocha return errors

### ISSUE THREAD

**Issue by do-n-khanh** [practicalmeteor/mocha#63]
I ran `C:\Meteor\base>meteor add practicalmeteor:mocha`
## and i got error

C:\Users\Khanh\AppData\Local.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Khanh\AppData\Local.meteor\packages\practicalmeteor_mocha\2.4.5_6\os.json'
    at Error (native)

**Comment by jsep** [comment]
Hello @do-n-khanh can you try to install the package again after a `meteor reset` ?.

This it's not a problem with package itself it's probably meteor's , I've installed without problems.

Closing this, if re-open the issue if still persists
