### ISSUE TITLE
Export does not work with the tests

### ISSUE THREAD

**Issue by theodorDiaconu** [practicalmeteor/mocha#68]
However, import works. Super weird. I have main.js, and I import ./collection.js. And I export something in collection.js and it fails like:

`W20160913-17:23:53.236(3)? (STDERR) /tmp/meteor-test-run8ojy8z/.meteor/local/build/programs/server/packages/local-test_cultofcoders_links.js:216
W20160913-17:23:53.236(3)? (STDERR) export default {
W20160913-17:23:53.238(3)? (STDERR) ^^^^^^
W20160913-17:23:53.238(3)? (STDERR) 
W20160913-17:23:53.239(3)? (STDERR) SyntaxError: Unexpected reserved word
W20160913-17:23:53.239(3)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20160913-17:23:53.239(3)? (STDERR)     at /tmp/meteor-test-run8ojy8z/.meteor/local/build/programs/server/boot.js:287:30
W20160913-17:23:53.240(3)? (STDERR)     at Array.forEach (native)
W20160913-17:23:53.242(3)? (STDERR)     at Function._.each._.forEach (/home/theodor/.meteor/packages/meteor-tool/.1.4.1_1.1clsk54++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160913-17:23:53.242(3)? (STDERR)     at /tmp/meteor-test-run8ojy8z/.meteor/local/build/programs/server/boot.js:128:5
=> Exited with code: 1`

**Comment by theodorDiaconu** [comment]
Update! it seems that if I import something in a test file. I have no ES6.

**Comment by jsep** [comment]
Hello @theodorDiaconu , make sure you are using the `ecmascript` package also under `Pacakge.onTest()`

I'm going to close this because it's not related to this package, it have to be posted in the meteor repo instead.

**Comment by theodorDiaconu** [comment]
@jsep I was using ecmascript. The issue was because I was in "tests" folder. Renaming it to "testing" solved the problem.
