### ISSUE TITLE
Error while installing mocha

### ISSUE THREAD

**Issue by ankibalyan** [practicalmeteor/mocha#72]
I'm trying to install `practicalmeteor:mocha` in `Meteor 1.4` getting and getting following error.

`/Users/.meteor/packages/ecmascript/.0.5.8.xrqpml++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165`

``````
throw error;
      ^
Error: EIO: i/o error, read
    at Error (native)```
``````

**Comment by ankibalyan** [comment]
Node version I'm using is
`node -v`
`v6.4.0`

**Comment by jsep** [comment]
Hello @ankibalyan this error is not related to this package itself, is a meteor issue instead, since meteor is   handling the installation problem.

I didn't have any problem installing mocha from scratch.

**Comment by ankibalyan** [comment]
@jsep But my app is working fine if I remove this, with no error. How can i figure it out, which what is causing this issue?
